# Model Training File

In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor 
import warnings

In [37]:
df = pd.read_csv('data/students_data.csv')

In [38]:
df.head()

   Gender Race_Ethnicity  ... Reading_Score Writing_Score
0    Male        Group C  ...            58            61
1  Female        Group C  ...            43            95
2    Male        Group C  ...            85            58
3    Male        Group D  ...            42            45
4    Male        Group D  ...            67            97

[5 rows x 8 columns]

In [39]:
X = df.drop(columns=['Math_Score'])
y = df['Math_Score']

In [40]:
# create a column transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="str").columns
cat_features = X.select_dtypes(include="str").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numerical_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
        ("StandardScaler", numerical_transformer, num_features),
    ]
)

In [41]:
X = preprocessor.fit_transform(X)

In [42]:
X.shape

(1000, 18)

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((800, 18), (200, 18))

### Create an Evaluate Function to give all metrices after model training

In [45]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2_square = r2_score(true, predicted)
    return mae, mse, rmse, r2_square

In [46]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [47]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbour Regression": KNeighborsRegressor(),
    "DecisionTreeRegressor": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(),
    "CatBoosting Regressor": CatBoostRegressor(),
    "AdaBoostRegressor": AdaBoostRegressor() 
}

model_list = []
r2_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)


    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print("Model Performance for Training Set")
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model Performance for Training Set
- Root Mean Squared Error: 17.8377
- Mean Absolute Error: 15.6307
- R2 Score: 0.0100
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 17.7674
- Mean Absolute Error: 15.2190
- R2 Score: 0.0045
===================================


Lasso
Model Performance for Training Set
- Root Mean Squared Error: 17.9278
- Mean Absolute Error: 15.7718
- R2 Score: 0.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 17.8173
- Mean Absolute Error: 15.2805
- R2 Score: -0.0011
===================================


Ridge
Model Performance for Training Set
- Root Mean Squared Error: 17.8377
- Mean Absolute Error: 15.6313
- R2 Score: 0.0100
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 17.7674
- Mean Absolute Error: 15.2191
- R2 Score: 0.0045
===================================


K-Neighbour Regression
Model Performance for Training Set
- Root Mean Squared Error: 16.3903
- Mean Absolute Error: 14.0573
- R2 Score: 0.1642
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 19.0360
- Mean Absolute Error: 15.9760
- R2 Score: -0.1427
===================================


DecisionTreeRegressor
Model Performance for Training Set
- Root Mean Squared Error: 0.4500
- Mean Absolute Error: 0.0225
- R2 Score: 0.9994
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 26.2083
- Mean Absolute Error: 21.9450
- R2 Score: -1.1660
===================================


Random Forest Regressor
Model Performance for Training Set
- Root Mean Squared Error: 7.2767
- Mean Absolute Error: 6.2144
- R2 Score: 0.8353
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 18.4421
- Mean Absolute Error: 15.6009
- R2 Score: -0.0725
===================================


XGBRegressor
Model Performance for Training Set
- Root Mean Squared Error: 1.6990
- Mean Absolute Error: 1.1979
- R2 Score: 0.9910
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 21.2755
- Mean Absolute Error: 17.5647
- R2 Score: -0.4274
===================================


Learning rate set to 0.039525
0:	learn: 17.8967924	total: 3.04ms	remaining: 3.04s
1:	learn: 17.8680995	total: 4.89ms	remaining: 2.44s
2:	learn: 17.8423406	total: 8.12ms	remaining: 2.7s
3:	learn: 17.8136588	total: 10ms	remaining: 2.5s
4:	learn: 17.7805763	total: 11.9ms	remaining: 2.37s
5:	learn: 17.7457066	total: 13.7ms	remaining: 2.27s
6:	learn: 17.7147627	total: 15.6ms	remaining: 2.21s
7:	learn: 17.6748380	total: 17.4ms	remaining: 2.16s
8:	learn: 17.6456533	total: 19.2ms	remaining: 2.11s
9:	learn: 17.6391316	total: 20.4ms	remaining: 2.02s
10:	learn: 17.6120063	total: 22.4ms	remaining: 2.01s
11:	learn: 17.5723782	total: 24.2ms	remaining: 1.99s
12:	learn: 17.5583366	total: 28ms	remaining: 2.13s
13:	learn: 17.5237029	total: 29.9ms	remaining: 2.11s
14:	learn: 17.5067568	total: 31.9ms	remaining: 2.09s
15:	learn: 17.4757958	total: 33.6ms	remaining: 2.07s
16:	learn: 17.4346910	total: 38.2ms	remaining: 2.21s
17:	learn: 17.4092736	total: 40.1ms	remaining: 2.19s
18:	learn: 17.3900588	total: 41.9ms	remaining: 2.17s
19:	learn: 17.3754504	total: 43.7ms	remaining: 2.14s
20:	learn: 17.3566920	total: 45.2ms	remaining: 2.11s
21:	learn: 17.3330618	total: 46.9ms	remaining: 2.08s
22:	learn: 17.3170294	total: 48.8ms	remaining: 2.07s
23:	learn: 17.2988632	total: 51ms	remaining: 2.08s
24:	learn: 17.2729608	total: 53ms	remaining: 2.07s
25:	learn: 17.2333762	total: 54.6ms	remaining: 2.05s
26:	learn: 17.2054894	total: 56.5ms	remaining: 2.04s
27:	learn: 17.1895894	total: 58.4ms	remaining: 2.03s
28:	learn: 17.1581308	total: 60.4ms	remaining: 2.02s
29:	learn: 17.1350068	total: 62.2ms	remaining: 2.01s
30:	learn: 17.0885590	total: 64.5ms	remaining: 2.02s
31:	learn: 17.0614257	total: 66.3ms	remaining: 2s
32:	learn: 17.0402501	total: 68.3ms	remaining: 2s
33:	learn: 17.0125473	total: 70.9ms	remaining: 2.02s
34:	learn: 16.9938014	total: 72.6ms	remaining: 2s
35:	learn: 16.9771406	total: 74.8ms	remaining: 2s
36:	learn: 16.9592508	total: 76.7ms	remaining: 2s
37:	learn: 16.9408940	total: 79.3ms	remaining: 2.01s
38:	learn: 16.9259102	total: 81.5ms	remaining: 2.01s
39:	learn: 16.9032682	total: 83.3ms	remaining: 2s
40:	learn: 16.8935791	total: 85.2ms	remaining: 1.99s
41:	learn: 16.8608460	total: 86.8ms	remaining: 1.98s
42:	learn: 16.8446373	total: 88.8ms	remaining: 1.98s
43:	learn: 16.8306330	total: 90.6ms	remaining: 1.97s
44:	learn: 16.8047810	total: 92.7ms	remaining: 1.97s
45:	learn: 16.7856681	total: 94.9ms	remaining: 1.97s
46:	learn: 16.7825569	total: 96.2ms	remaining: 1.95s
47:	learn: 16.7627794	total: 98.1ms	remaining: 1.95s
48:	learn: 16.7439783	total: 100ms	remaining: 1.94s
49:	learn: 16.7309444	total: 102ms	remaining: 1.94s
50:	learn: 16.7051262	total: 104ms	remaining: 1.93s
51:	learn: 16.6825097	total: 105ms	remaining: 1.92s
52:	learn: 16.6549535	total: 107ms	remaining: 1.92s
53:	learn: 16.6293389	total: 109ms	remaining: 1.91s
54:	learn: 16.6060670	total: 112ms	remaining: 1.93s
55:	learn: 16.5899404	total: 114ms	remaining: 1.93s
56:	learn: 16.5679196	total: 116ms	remaining: 1.93s
57:	learn: 16.5449713	total: 118ms	remaining: 1.92s
58:	learn: 16.5237972	total: 120ms	remaining: 1.92s
59:	learn: 16.4919004	total: 123ms	remaining: 1.92s
60:	learn: 16.4807239	total: 124ms	remaining: 1.91s
61:	learn: 16.4577529	total: 126ms	remaining: 1.91s
62:	learn: 16.4445067	total: 128ms	remaining: 1.91s
63:	learn: 16.4203039	total: 130ms	remaining: 1.9s
64:	learn: 16.3948283	total: 132ms	remaining: 1.9s
65:	learn: 16.3869321	total: 134ms	remaining: 1.89s
66:	learn: 16.3595604	total: 136ms	remaining: 1.89s
67:	learn: 16.3422053	total: 138ms	remaining: 1.89s
68:	learn: 16.3163158	total: 140ms	remaining: 1.88s
69:	learn: 16.3047804	total: 142ms	remaining: 1.89s
70:	learn: 16.2916784	total: 144ms	remaining: 1.89s
71:	learn: 16.2878254	total: 146ms	remaining: 1.88s
72:	learn: 16.2755348	total: 147ms	remaining: 1.87s
73:	learn: 16.2528534	total: 150ms	remaining: 1.87s
74:	learn: 16.2316374	total: 152ms	remaining: 1.87s
75:	learn: 16.2154366	total: 155ms	remaining: 1.89s
76:	learn: 16.1961679	total: 157ms	remaining: 1.89s
77:	learn: 16.1807490	total: 159ms	remaining: 1.88s
78:	learn: 16.1686021	total: 161ms	remaining: 1.88s
79:	learn: 16.1466246	total: 165ms	remaining: 1.89s
80:	learn: 16.1245486	total: 167ms	remaining: 1.89s
81:	learn: 16.1138343	total: 169ms	remaining: 1.89s
82:	learn: 16.1025511	total: 170ms	remaining: 1.88s
83:	learn: 16.0896172	total: 172ms	remaining: 1.88s
84:	learn: 16.0624138	total: 174ms	remaining: 1.87s
85:	learn: 16.0452725	total: 176ms	remaining: 1.87s
86:	learn: 16.0255386	total: 178ms	remaining: 1.87s
87:	learn: 15.9990825	total: 180ms	remaining: 1.87s
88:	learn: 15.9765289	total: 182ms	remaining: 1.86s
89:	learn: 15.9512713	total: 184ms	remaining: 1.86s
90:	learn: 15.9233599	total: 186ms	remaining: 1.86s
91:	learn: 15.9138886	total: 188ms	remaining: 1.85s
92:	learn: 15.9112594	total: 189ms	remaining: 1.84s
93:	learn: 15.8954909	total: 191ms	remaining: 1.84s
94:	learn: 15.8798497	total: 193ms	remaining: 1.84s
95:	learn: 15.8676531	total: 195ms	remaining: 1.83s
96:	learn: 15.8655341	total: 196ms	remaining: 1.83s
97:	learn: 15.8554857	total: 198ms	remaining: 1.83s
98:	learn: 15.8389718	total: 200ms	remaining: 1.82s
99:	learn: 15.8261882	total: 202ms	remaining: 1.82s
100:	learn: 15.7985794	total: 204ms	remaining: 1.81s
101:	learn: 15.7860063	total: 206ms	remaining: 1.82s
102:	learn: 15.7750341	total: 208ms	remaining: 1.81s
103:	learn: 15.7565120	total: 210ms	remaining: 1.81s
104:	learn: 15.7333975	total: 212ms	remaining: 1.81s
105:	learn: 15.7134385	total: 214ms	remaining: 1.81s
106:	learn: 15.7040044	total: 216ms	remaining: 1.8s
107:	learn: 15.6945686	total: 218ms	remaining: 1.8s
108:	learn: 15.6812474	total: 220ms	remaining: 1.8s
109:	learn: 15.6502080	total: 223ms	remaining: 1.8s
110:	learn: 15.6385712	total: 225ms	remaining: 1.8s
111:	learn: 15.6369594	total: 226ms	remaining: 1.79s
112:	learn: 15.6301775	total: 228ms	remaining: 1.79s
113:	learn: 15.6147127	total: 230ms	remaining: 1.79s
114:	learn: 15.5989053	total: 232ms	remaining: 1.78s
115:	learn: 15.5853833	total: 234ms	remaining: 1.79s
116:	learn: 15.5749793	total: 236ms	remaining: 1.78s
117:	learn: 15.5628461	total: 239ms	remaining: 1.78s
118:	learn: 15.5504150	total: 241ms	remaining: 1.78s
119:	learn: 15.5317218	total: 243ms	remaining: 1.78s
120:	learn: 15.5082066	total: 245ms	remaining: 1.78s
121:	learn: 15.4878895	total: 247ms	remaining: 1.77s
122:	learn: 15.4649638	total: 249ms	remaining: 1.78s
123:	learn: 15.4551778	total: 251ms	remaining: 1.78s
124:	learn: 15.4419379	total: 254ms	remaining: 1.77s
125:	learn: 15.4194660	total: 257ms	remaining: 1.78s
126:	learn: 15.3964352	total: 259ms	remaining: 1.78s
127:	learn: 15.3753978	total: 261ms	remaining: 1.77s
128:	learn: 15.3631861	total: 263ms	remaining: 1.78s
129:	learn: 15.3468447	total: 266ms	remaining: 1.78s
130:	learn: 15.3342896	total: 268ms	remaining: 1.78s
131:	learn: 15.3130461	total: 271ms	remaining: 1.78s
132:	learn: 15.2924597	total: 273ms	remaining: 1.78s
133:	learn: 15.2720690	total: 276ms	remaining: 1.78s
134:	learn: 15.2505737	total: 278ms	remaining: 1.78s
135:	learn: 15.2360709	total: 281ms	remaining: 1.78s
136:	learn: 15.2280522	total: 283ms	remaining: 1.78s
137:	learn: 15.2111386	total: 285ms	remaining: 1.78s
138:	learn: 15.1951711	total: 288ms	remaining: 1.78s
139:	learn: 15.1761370	total: 290ms	remaining: 1.78s
140:	learn: 15.1750084	total: 291ms	remaining: 1.77s
141:	learn: 15.1559688	total: 294ms	remaining: 1.78s
142:	learn: 15.1432419	total: 297ms	remaining: 1.78s
143:	learn: 15.1335853	total: 299ms	remaining: 1.78s
144:	learn: 15.1189241	total: 310ms	remaining: 1.83s
145:	learn: 15.0943638	total: 316ms	remaining: 1.85s
146:	learn: 15.0848564	total: 319ms	remaining: 1.85s
147:	learn: 15.0672300	total: 325ms	remaining: 1.87s
148:	learn: 15.0533781	total: 328ms	remaining: 1.87s
149:	learn: 15.0443865	total: 332ms	remaining: 1.88s
150:	learn: 15.0253997	total: 336ms	remaining: 1.89s
151:	learn: 15.0114711	total: 338ms	remaining: 1.89s
152:	learn: 15.0000774	total: 385ms	remaining: 2.13s
153:	learn: 14.9875469	total: 387ms	remaining: 2.13s
154:	learn: 14.9685805	total: 394ms	remaining: 2.15s
155:	learn: 14.9565207	total: 426ms	remaining: 2.31s
156:	learn: 14.9357029	total: 436ms	remaining: 2.34s
157:	learn: 14.9226383	total: 438ms	remaining: 2.33s
158:	learn: 14.9164698	total: 441ms	remaining: 2.33s
159:	learn: 14.8974343	total: 443ms	remaining: 2.32s
160:	learn: 14.8764901	total: 445ms	remaining: 2.32s
161:	learn: 14.8694984	total: 448ms	remaining: 2.31s
162:	learn: 14.8539158	total: 450ms	remaining: 2.31s
163:	learn: 14.8277056	total: 452ms	remaining: 2.3s
164:	learn: 14.8124304	total: 454ms	remaining: 2.3s
165:	learn: 14.7918909	total: 458ms	remaining: 2.3s
166:	learn: 14.7657477	total: 485ms	remaining: 2.42s
167:	learn: 14.7494570	total: 487ms	remaining: 2.41s
168:	learn: 14.7386980	total: 490ms	remaining: 2.41s
169:	learn: 14.7187016	total: 495ms	remaining: 2.42s
170:	learn: 14.7095423	total: 497ms	remaining: 2.41s
171:	learn: 14.6991074	total: 502ms	remaining: 2.41s
172:	learn: 14.6857368	total: 504ms	remaining: 2.41s
173:	learn: 14.6725010	total: 507ms	remaining: 2.4s
174:	learn: 14.6506939	total: 510ms	remaining: 2.41s
175:	learn: 14.6441146	total: 530ms	remaining: 2.48s
176:	learn: 14.6344448	total: 533ms	remaining: 2.48s
177:	learn: 14.6191262	total: 544ms	remaining: 2.51s
178:	learn: 14.6092690	total: 547ms	remaining: 2.51s
179:	learn: 14.5950158	total: 550ms	remaining: 2.5s
180:	learn: 14.5897644	total: 552ms	remaining: 2.5s
181:	learn: 14.5854613	total: 556ms	remaining: 2.5s
182:	learn: 14.5721073	total: 558ms	remaining: 2.49s
183:	learn: 14.5656180	total: 561ms	remaining: 2.49s
184:	learn: 14.5490493	total: 566ms	remaining: 2.49s
185:	learn: 14.5385071	total: 568ms	remaining: 2.48s
186:	learn: 14.5272078	total: 570ms	remaining: 2.48s
187:	learn: 14.5091600	total: 574ms	remaining: 2.48s
188:	learn: 14.4940938	total: 577ms	remaining: 2.48s
189:	learn: 14.4824533	total: 581ms	remaining: 2.48s
190:	learn: 14.4704882	total: 588ms	remaining: 2.49s
191:	learn: 14.4588716	total: 591ms	remaining: 2.49s
192:	learn: 14.4412169	total: 594ms	remaining: 2.48s
193:	learn: 14.4272274	total: 597ms	remaining: 2.48s
194:	learn: 14.4137974	total: 599ms	remaining: 2.47s
195:	learn: 14.4026711	total: 601ms	remaining: 2.47s
196:	learn: 14.3882804	total: 609ms	remaining: 2.48s
197:	learn: 14.3740632	total: 613ms	remaining: 2.48s
198:	learn: 14.3666648	total: 616ms	remaining: 2.48s
199:	learn: 14.3345976	total: 619ms	remaining: 2.47s
200:	learn: 14.3248248	total: 622ms	remaining: 2.47s
201:	learn: 14.3158468	total: 624ms	remaining: 2.46s
202:	learn: 14.3071809	total: 626ms	remaining: 2.46s
203:	learn: 14.2909768	total: 629ms	remaining: 2.45s
204:	learn: 14.2751412	total: 631ms	remaining: 2.45s
205:	learn: 14.2631066	total: 633ms	remaining: 2.44s
206:	learn: 14.2496160	total: 637ms	remaining: 2.44s
207:	learn: 14.2389715	total: 640ms	remaining: 2.44s
208:	learn: 14.2299193	total: 642ms	remaining: 2.43s
209:	learn: 14.2180797	total: 644ms	remaining: 2.42s
210:	learn: 14.2094618	total: 647ms	remaining: 2.42s
211:	learn: 14.2044987	total: 650ms	remaining: 2.41s
212:	learn: 14.1904196	total: 652ms	remaining: 2.41s
213:	learn: 14.1780127	total: 654ms	remaining: 2.4s
214:	learn: 14.1694591	total: 657ms	remaining: 2.4s
215:	learn: 14.1572242	total: 659ms	remaining: 2.39s
216:	learn: 14.1422868	total: 661ms	remaining: 2.39s
217:	learn: 14.1301020	total: 664ms	remaining: 2.38s
218:	learn: 14.1159737	total: 666ms	remaining: 2.38s
219:	learn: 14.1069347	total: 668ms	remaining: 2.37s
220:	learn: 14.0997344	total: 671ms	remaining: 2.36s
221:	learn: 14.0802651	total: 673ms	remaining: 2.36s
222:	learn: 14.0705100	total: 675ms	remaining: 2.35s
223:	learn: 14.0638288	total: 678ms	remaining: 2.35s
224:	learn: 14.0526805	total: 680ms	remaining: 2.34s
225:	learn: 14.0388428	total: 682ms	remaining: 2.33s
226:	learn: 14.0252016	total: 684ms	remaining: 2.33s
227:	learn: 14.0175547	total: 686ms	remaining: 2.32s
228:	learn: 14.0037279	total: 689ms	remaining: 2.32s
229:	learn: 13.9942787	total: 691ms	remaining: 2.31s
230:	learn: 13.9852758	total: 695ms	remaining: 2.31s
231:	learn: 13.9712129	total: 699ms	remaining: 2.31s
232:	learn: 13.9569977	total: 701ms	remaining: 2.31s
233:	learn: 13.9410497	total: 704ms	remaining: 2.3s
234:	learn: 13.9321813	total: 706ms	remaining: 2.3s
235:	learn: 13.9122123	total: 709ms	remaining: 2.29s
236:	learn: 13.8970172	total: 712ms	remaining: 2.29s
237:	learn: 13.8816681	total: 714ms	remaining: 2.29s
238:	learn: 13.8752138	total: 717ms	remaining: 2.28s
239:	learn: 13.8524739	total: 720ms	remaining: 2.28s
240:	learn: 13.8451670	total: 723ms	remaining: 2.28s
241:	learn: 13.8302408	total: 725ms	remaining: 2.27s
242:	learn: 13.8162308	total: 728ms	remaining: 2.27s
243:	learn: 13.8060463	total: 730ms	remaining: 2.26s
244:	learn: 13.7986524	total: 732ms	remaining: 2.25s
245:	learn: 13.7899387	total: 735ms	remaining: 2.25s
246:	learn: 13.7792756	total: 737ms	remaining: 2.25s
247:	learn: 13.7709206	total: 740ms	remaining: 2.24s
248:	learn: 13.7606973	total: 743ms	remaining: 2.24s
249:	learn: 13.7471698	total: 745ms	remaining: 2.23s
250:	learn: 13.7243638	total: 747ms	remaining: 2.23s
251:	learn: 13.7110799	total: 749ms	remaining: 2.22s
252:	learn: 13.6986836	total: 752ms	remaining: 2.22s
253:	learn: 13.6863150	total: 754ms	remaining: 2.21s
254:	learn: 13.6790016	total: 756ms	remaining: 2.21s
255:	learn: 13.6679124	total: 758ms	remaining: 2.2s
256:	learn: 13.6604482	total: 760ms	remaining: 2.2s
257:	learn: 13.6499876	total: 763ms	remaining: 2.19s
258:	learn: 13.6408433	total: 765ms	remaining: 2.19s
259:	learn: 13.6286395	total: 767ms	remaining: 2.18s
260:	learn: 13.6178067	total: 769ms	remaining: 2.18s
261:	learn: 13.6093721	total: 771ms	remaining: 2.17s
262:	learn: 13.6016912	total: 775ms	remaining: 2.17s
263:	learn: 13.5916104	total: 777ms	remaining: 2.17s
264:	learn: 13.5795790	total: 779ms	remaining: 2.16s
265:	learn: 13.5666928	total: 781ms	remaining: 2.15s
266:	learn: 13.5515245	total: 784ms	remaining: 2.15s
267:	learn: 13.5455249	total: 786ms	remaining: 2.15s
268:	learn: 13.5348300	total: 789ms	remaining: 2.14s
269:	learn: 13.5239563	total: 791ms	remaining: 2.14s
270:	learn: 13.5133904	total: 793ms	remaining: 2.13s
271:	learn: 13.5031405	total: 795ms	remaining: 2.13s
272:	learn: 13.4906346	total: 797ms	remaining: 2.12s
273:	learn: 13.4839368	total: 800ms	remaining: 2.12s
274:	learn: 13.4717949	total: 802ms	remaining: 2.11s
275:	learn: 13.4545590	total: 804ms	remaining: 2.11s
276:	learn: 13.4379068	total: 806ms	remaining: 2.1s
277:	learn: 13.4272517	total: 808ms	remaining: 2.1s
278:	learn: 13.4175630	total: 810ms	remaining: 2.09s
279:	learn: 13.4089924	total: 812ms	remaining: 2.09s
280:	learn: 13.3996883	total: 814ms	remaining: 2.08s
281:	learn: 13.3852772	total: 817ms	remaining: 2.08s
282:	learn: 13.3772600	total: 819ms	remaining: 2.07s
283:	learn: 13.3674682	total: 821ms	remaining: 2.07s
284:	learn: 13.3560342	total: 823ms	remaining: 2.06s
285:	learn: 13.3382136	total: 826ms	remaining: 2.06s
286:	learn: 13.3256740	total: 829ms	remaining: 2.06s
287:	learn: 13.3138071	total: 831ms	remaining: 2.05s
288:	learn: 13.3019795	total: 833ms	remaining: 2.05s
289:	learn: 13.2917554	total: 835ms	remaining: 2.04s
290:	learn: 13.2830036	total: 837ms	remaining: 2.04s
291:	learn: 13.2715532	total: 839ms	remaining: 2.03s
292:	learn: 13.2627555	total: 841ms	remaining: 2.03s
293:	learn: 13.2480250	total: 843ms	remaining: 2.02s
294:	learn: 13.2398198	total: 845ms	remaining: 2.02s
295:	learn: 13.2259732	total: 847ms	remaining: 2.02s
296:	learn: 13.2137165	total: 849ms	remaining: 2.01s
297:	learn: 13.2015781	total: 853ms	remaining: 2.01s
298:	learn: 13.1888610	total: 855ms	remaining: 2s
299:	learn: 13.1738265	total: 857ms	remaining: 2s
300:	learn: 13.1629743	total: 860ms	remaining: 2s
301:	learn: 13.1561742	total: 862ms	remaining: 1.99s
302:	learn: 13.1486355	total: 864ms	remaining: 1.99s
303:	learn: 13.1329823	total: 867ms	remaining: 1.99s
304:	learn: 13.1230643	total: 870ms	remaining: 1.98s
305:	learn: 13.1131829	total: 872ms	remaining: 1.98s
306:	learn: 13.1003403	total: 876ms	remaining: 1.98s
307:	learn: 13.0860427	total: 879ms	remaining: 1.97s
308:	learn: 13.0754381	total: 881ms	remaining: 1.97s
309:	learn: 13.0701635	total: 883ms	remaining: 1.96s
310:	learn: 13.0605839	total: 885ms	remaining: 1.96s
311:	learn: 13.0524286	total: 887ms	remaining: 1.96s
312:	learn: 13.0444367	total: 889ms	remaining: 1.95s
313:	learn: 13.0311086	total: 892ms	remaining: 1.95s
314:	learn: 13.0250798	total: 894ms	remaining: 1.94s
315:	learn: 13.0147918	total: 896ms	remaining: 1.94s
316:	learn: 12.9945870	total: 898ms	remaining: 1.94s
317:	learn: 12.9866411	total: 900ms	remaining: 1.93s
318:	learn: 12.9710530	total: 904ms	remaining: 1.93s
319:	learn: 12.9534186	total: 906ms	remaining: 1.93s
320:	learn: 12.9449525	total: 908ms	remaining: 1.92s
321:	learn: 12.9384217	total: 910ms	remaining: 1.92s
322:	learn: 12.9268943	total: 912ms	remaining: 1.91s
323:	learn: 12.9163296	total: 914ms	remaining: 1.91s
324:	learn: 12.9007612	total: 917ms	remaining: 1.9s
325:	learn: 12.8913964	total: 921ms	remaining: 1.9s
326:	learn: 12.8825859	total: 922ms	remaining: 1.9s
327:	learn: 12.8695912	total: 925ms	remaining: 1.89s
328:	learn: 12.8582332	total: 927ms	remaining: 1.89s
329:	learn: 12.8497399	total: 929ms	remaining: 1.89s
330:	learn: 12.8379330	total: 933ms	remaining: 1.88s
331:	learn: 12.8290539	total: 935ms	remaining: 1.88s
332:	learn: 12.8148174	total: 937ms	remaining: 1.88s
333:	learn: 12.8031106	total: 940ms	remaining: 1.87s
334:	learn: 12.7907403	total: 943ms	remaining: 1.87s
335:	learn: 12.7854216	total: 946ms	remaining: 1.87s

In [48]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

                Model Name  R2_Score
2                    Ridge  0.004547
0        Linear Regression  0.004546
8        AdaBoostRegressor -0.000380
1                    Lasso -0.001061
5  Random Forest Regressor -0.072495
3   K-Neighbour Regression -0.142687
7    CatBoosting Regressor -0.210665
6             XGBRegressor -0.427360
4    DecisionTreeRegressor -1.165971